[project]
name = "python-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.128.1",
    "sentencepiece>=0.2.1",
    "torch>=2.10.0",
    "transformers>=5.0.0",
]
